const state={products:[],cat:'Todos',q:''};
const cats=document.querySelector('#cats'),grid=document.querySelector('#grid'),search=document.querySelector('#search');
const IMG={
 iPhone:'https://www.apple.com/v/iphone/home/cj/images/overview/consider/innovation__fmir5mp9zpay_large.jpg',
 iPhone18:'https://www.apple.com/v/homepage/images/iphone-18-pro/a/hero_iphone_18_pro_preorder__dd68unjbzswi_large.jpg',
 AirPods:'https://www.apple.com/v/airpods/af/images/overview/hero_endframe__calpooy4ucr6_large.jpg',
 iPad:'https://www.apple.com/v/ipad-pro/aw/images/overview/hero/hero_endframe__du5kcy4qnxkm_large.jpg',
 MacBook:'https://www.apple.com/v/homepage/images/macbook-air-m5/a/promo_macbook_air_m5__e5xk2yysqiie_large.jpg',
 Watch:'https://www.apple.com/la/homepage/built/heroes/26_apple-watch-series-12_09/images/hero_apple_watch_series_12_preorder__cv2wd7ow8926_large.jpg',
 AirTag:'https://store.storeimages.cdn-apple.com/1/as-images.apple.com/is/airtag-alp-featurecard-airtag-large_GEO_EMEA?.v=NXA5QU9wT3dhaUJXdTRmQ2FHWDkvS2NKYzlabFZKQmxLYzFwc2RtYklEMmNMWXp5bzJaTUhpS2ZWb0NFbHM4a2pKVTc5angwREZSS1N2cWRKRUhKQXpBSHlqQStCOGVBOUJkSkVqU0hLTkRNaUh6akEyWXNIQXFNRkMwbTZIam5mbW94YnYxc1YvNXZ4emJGL0IxNFp3&fmt=p-jpg&hei=1360&qlt=80&traceId=1&wid=2520'
};
const rows=[
['iPhone 18 Pro','iPhone','256 GB / 512 GB','Borgoña · Blanco · Negro','iPhone18'],['iPhone 18 Pro Max','iPhone','256 GB / 512 GB','Borgoña · Blanco · Negro','iPhone18'],['iPhone Air','iPhone','256 GB / 512 GB','Azul cielo · Oro claro · Blanco nube · Negro','iPhone'],['iPhone 17 Pro','iPhone','256 GB / 512 GB / 1 TB','Naranja cósmico · Plata · Azul','iPhone'],['iPhone 17 Pro Max','iPhone','256 GB / 512 GB / 1 TB','Naranja cósmico · Plata · Azul','iPhone'],['iPhone 17','iPhone','256 GB / 512 GB','Lavanda · Azul · Blanco · Negro','iPhone'],['iPhone 17e','iPhone','256 GB','Negro · Blanco','iPhone'],['iPhone 16 Pro','iPhone','128 GB / 256 GB / 512 GB / 1 TB','Titanio natural · Negro · Blanco · Desierto','iPhone'],['iPhone 16 Pro Max','iPhone','256 GB / 512 GB / 1 TB','Titanio natural · Negro · Blanco · Desierto','iPhone'],['iPhone 16','iPhone','128 GB / 256 GB / 512 GB','Ultramarino · Verde azulado · Rosa · Blanco · Negro','iPhone'],['iPhone 16 Plus','iPhone','128 GB / 256 GB / 512 GB','Ultramarino · Verde azulado · Rosa · Blanco · Negro','iPhone'],['iPhone 16e','iPhone','128 GB / 256 GB / 512 GB','Negro · Blanco','iPhone'],['iPhone 15 Pro','iPhone','128 GB / 256 GB / 512 GB / 1 TB','Titanio natural · Azul · Blanco · Negro','iPhone'],['iPhone 15 Pro Max','iPhone','256 GB / 512 GB / 1 TB','Titanio natural · Azul · Blanco · Negro','iPhone'],['iPhone 15','iPhone','128 GB / 256 GB / 512 GB','Rosa · Amarillo · Verde · Azul · Negro','iPhone'],['iPhone 15 Plus','iPhone','128 GB / 256 GB / 512 GB','Rosa · Amarillo · Verde · Azul · Negro','iPhone'],['iPhone 14 Pro','iPhone','128 GB / 256 GB / 512 GB / 1 TB','Negro · Plata · Oro · Morado','iPhone'],['iPhone 14 Pro Max','iPhone','128 GB / 256 GB / 512 GB / 1 TB','Negro · Plata · Oro · Morado','iPhone'],['iPhone 14','iPhone','128 GB / 256 GB / 512 GB','Azul · Morado · Medianoche · Blanco · Rojo','iPhone'],['iPhone 14 Plus','iPhone','128 GB / 256 GB / 512 GB','Azul · Morado · Medianoche · Blanco · Rojo','iPhone'],['iPhone 13 Pro','iPhone','128 GB / 256 GB / 512 GB / 1 TB','Grafito · Oro · Plata · Azul','iPhone'],['iPhone 13 Pro Max','iPhone','128 GB / 256 GB / 512 GB / 1 TB','Grafito · Oro · Plata · Azul','iPhone'],['iPhone 13','iPhone','128 GB / 256 GB / 512 GB','Medianoche · Azul · Rosa · Blanco · Rojo · Verde','iPhone'],['iPhone 12 Pro','iPhone','128 GB / 256 GB / 512 GB','Grafito · Plata · Oro · Azul Pacífico','iPhone'],['iPhone 12','iPhone','64 GB / 128 GB / 256 GB','Negro · Blanco · Azul · Verde · Rojo · Morado','iPhone'],['iPhone 11','iPhone','64 GB / 128 GB / 256 GB','Negro · Verde · Amarillo · Morado · Rojo · Blanco','iPhone'],
['AirPods 5','AirPods','—','Blanco','AirPods'],['AirPods 5 con estuche de carga inalámbrica','AirPods','—','Blanco','AirPods'],['AirPods Pro 3','AirPods','—','Blanco','AirPods'],['AirPods Max 2','AirPods','—','Varios colores','AirPods'],['AirPods 4','AirPods','—','Blanco','AirPods'],['AirPods 4 con Cancelación Activa de Ruido','AirPods','—','Blanco','AirPods'],
['Apple Watch Series 12','Apple Watch','42 mm / 46 mm','Varios acabados','Watch'],['Apple Watch Ultra 4','Apple Watch','49 mm','Titanio','Watch'],['Apple Watch Series 11','Apple Watch','42 mm / 46 mm','Varios acabados','Watch'],['Apple Watch Ultra 3','Apple Watch','49 mm','Titanio','Watch'],['Apple Watch SE 3','Apple Watch','40 mm / 44 mm','Aluminio','Watch'],['Apple Watch Series 10','Apple Watch','42 mm / 46 mm','Varios acabados','Watch'],['Apple Watch Ultra 2','Apple Watch','49 mm','Titanio','Watch'],['Apple Watch SE 2','Apple Watch','40 mm / 44 mm','Aluminio','Watch'],
['iPad Pro','iPad','11” / 13” · 256 GB a 2 TB','Negro espacial · Plata','iPad'],['iPad Air','iPad','11” / 13” · 128 GB a 1 TB','Azul · Morado · Blanco estelar · Gris espacial','iPad'],['iPad (A16)','iPad','128 GB / 256 GB / 512 GB','Azul · Rosa · Amarillo · Plata','iPad'],['iPad mini','iPad','128 GB / 256 GB / 512 GB','Azul · Morado · Blanco estelar · Gris espacial','iPad'],
['MacBook Neo','MacBook','256 GB / 512 GB','Varios acabados','MacBook'],['MacBook Air','MacBook','13” / 15” · 512 GB a 4 TB','Azul cielo · Plata · Blanco estelar · Medianoche','MacBook'],['MacBook Pro','MacBook','14” / 16” · 1 TB a 8 TB','Negro espacial · Plata','MacBook'],['iMac','MacBook','24”','Varios colores','MacBook'],['Mac mini','MacBook','—','Plata','MacBook'],['Mac Studio','MacBook','—','Plata','MacBook'],
['AirTag','AirTag','1 unidad','Blanco / Plata','AirTag'],['AirTag x4','AirTag','Pack de 4','Blanco / Plata','AirTag'],['Apple Pencil Pro','Accesorios','—','Blanco','AirPods'],['Apple Pencil (USB-C)','Accesorios','—','Blanco','AirPods'],['Magic Mouse','Accesorios','—','Blanco · Negro','AirPods'],['Cables USB-C','Accesorios','—','Blanco','AirPods'],['Cables USB-C a Lightning','Accesorios','—','Blanco','AirPods'],['Cargador USB-C','Accesorios','—','Blanco','AirPods']
];
const products=rows.map(([name,category,storage,color,key])=>({name,category,storage,color,image:IMG[key]}));
function esc(s){return String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c]));}
function render(){const q=state.q.trim();const ps=state.products.filter(p=>(state.cat==='Todos'||p.category===state.cat)&&(p.name+' '+p.storage+' '+p.color+' '+p.category).toLowerCase().includes(q));grid.innerHTML=ps.map(p=>`<article class="card"><div><div class="pic"><img src="${p.image}" alt="${esc(p.name)}" loading="lazy" onerror="this.style.display='none';this.nextElementSibling.style.display='grid"><div class="emojiFallback">${p.category==='iPhone'?'📱':p.category==='iPad'?'▣':p.category==='MacBook'?'💻':p.category==='AirPods'?'🎧':p.category==='Apple Watch'?'⌚':'📍'}</div></div><div class="tag">${esc(p.category)}</div><h3>${esc(p.name)}</h3><div class="meta"><b>Capacidad:</b> ${esc(p.storage)}</div><div class="meta"><b>Colores:</b> ${esc(p.color)}</div></div><div class="cardBottom"><span>Consultar disponibilidad</span><a class="consultBtn" href="#contacto">Consultar</a></div></article>`).join('')||'<p>No encontramos productos.</p>';}
state.products=products;const cs=['Todos',...new Set(products.map(p=>p.category))];cats.innerHTML=cs.map(c=>`<button class="cat ${c==='Todos'?'active':''}" data-c="${c}">${c}</button>`).join('');document.querySelectorAll('.cat').forEach(b=>b.onclick=()=>{state.cat=b.dataset.c;document.querySelectorAll('.cat').forEach(x=>x.classList.remove('active'));b.classList.add('active');render();});render();search.oninput=e=>{state.q=e.target.value.toLowerCase();render();};
const wa=document.body.dataset.whatsapp||'';if(wa){document.querySelector('#waHero').href=`https://wa.me/${wa}?text=${encodeURIComponent('Hola nico.ioshop! Quiero consultar por un producto.')}`;document.querySelector('#waCanje').href=`https://wa.me/${wa}?text=${encodeURIComponent('Hola nico.ioshop! Quiero consultar por Plan Canje.')}`;}
